language: cpp
sudo: required
compiler : g++

addons:
  apt:
    packages:
      - doxygen
      - cppcheck
      
before_script:
    - mkdir build 
    - cd build 
    
script: 
    - cmake -DSTRINGOZZI_TRAVIS_BUILD=TRUE -DCMAKE_BUILD_TYPE=Debug -DARCH=x64  ..
    - cmake --build . --config debug
    - cppcheck  --verbose --enable=all ../src/*.cpp ../include/*.h ../test/*.cpp
    - ../bin.tmp/Linux/Debug/x86/stringozzi.test
    - doxygen ../docs/Doxyfile

after_success:
    - cd ${TRAVIS_BUILD_DIR}
    - lcov --directory . --capture --output-file coverage.info # capture coverage info
    - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
    - lcov --list coverage.info #debug info
    - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"